version: '3.8'

services:
  notion-mcp-server:
    container_name: notion-mcp-server
    image: notion-mcp-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4579:4579"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - notion-mcp-network
      - local-ai-packaged_demo

networks:
  notion-mcp-network:
    driver: bridge
  local-ai-packaged_demo:
    external: true 